---
- hosts: cloud
  gather_facts: false
  become: false
  vars:
    test_os: ""
    arch: "{{ lookup('env', 'ARCH') | default('x86_64', true) }}"
    flavor:
      x86_64: "n2-standard-2"
      aarch64: "t2a-standard-1"
    ssh_key_pub: ""
    inventory_file: ""
    download_node: "{{ lookup('env', 'DOWNLOAD_NODE') | default('', true) }}"

  tasks:
    - set_fact:
        random_num: "{{ 9999 | random(start=1001) }}"
    - set_fact:
        instance_name: "bootc-gcp-{{ test_os }}-{{ random_num }}"

    - name: gcloud/gsutil - authorizing with a service account
      command:
        "/usr/bin/gcloud auth activate-service-account \
        --key-file={{ lookup('env', 'GCP_SERVICE_ACCOUNT_FILE') }}"

    - name: Create gcp key file
      shell: sed "s/ssh-rsa/cloud-user:ssh-rsa/" "{{ ssh_key_pub }}" > "{{ ssh_key_pub }}.gcp_key"
      when: "'centos' in test_os or 'rhel' in test_os"

    - set_fact:
        image_args: "--image-family=centos-stream-9 --image-project=centos-cloud"
      when: "'centos' in test_os"

    - name: Get RHEL GCP image name
      shell: |
        /usr/bin/gcloud compute images list \
          --project={{ lookup('env', 'GCP_PROJECT') }} \
          --filter="labels.project=bootc AND labels.test_os={{ test_os }} AND labels.arch={{ arch }}" \
          --format json | jq -r '.[0].name'
      register: result_image_name
      when: "'rhel' in test_os"

    - set_fact:
        image_args: "--image={{ result_image_name.stdout }}"
      when: "'rhel' in test_os"

    - name: Create gcp instance
      command:
        /usr/bin/gcloud compute instances create {{ instance_name }} \
          --zone=us-central1-a \
          --machine-type={{ flavor[arch] }} \
          --boot-disk-auto-delete \
          --boot-disk-size=80GB \
          --metadata-from-file=ssh-keys={{ ssh_key_pub }}.gcp_key \
          --metadata=block-project-ssh-keys=TRUE \
          --provisioning-model=SPOT \
          {{ image_args }} \
          --project={{ lookup('env', 'GCP_PROJECT') }}

    - name: Makre sure instance is running
      shell: |
        /usr/bin/gcloud compute instances list \
          --project={{ lookup('env', 'GCP_PROJECT') }} \
          --filter="name={{ instance_name }}" \
          --format json | jq -r '.[0].status'
      register: instance_status_result
      retries: 20
      until: instance_status_result.stdout == "RUNNING"

    - name: Makre sure instance is having ip address
      shell: |
        /usr/bin/gcloud compute instances list \
          --project={{ lookup('env', 'GCP_PROJECT') }} \
          --filter="name={{ instance_name }}" \
          --format json | jq -r '.[0].networkInterfaces[0].accessConfigs[0].natIP'
      register: instance_ip_result
      retries: 20
      until: instance_ip_result.stdout != ""

    - set_fact:
        instance_ip: "{{ instance_ip_result.stdout }}"
      when:
        - instance_ip_result is succeeded

    - name: Waits until instance is reachable
      wait_for:
        host: "{{ instance_ip }}"
        port: 22
        search_regex: OpenSSH
        delay: 10
      retries: 30
      register: result_ssh_check
      until: result_ssh_check is success

    - name: Add instance ip into host group guest
      add_host:
        name: "{{ instance_ip }}"
        groups: guest

    - name: Wait 10 seconds for gcp instance
      wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Write instance ip to inventory file
      community.general.ini_file:
        path: "{{ inventory_file }}"
        section: guest
        option: guest ansible_host
        value: "{{ instance_ip }}"
        no_extra_spaces: true

    - name: Write random number to inventory file
      community.general.ini_file:
        path: "{{ inventory_file }}"
        section: cloud:vars
        option: random_num
        value: "{{ random_num }}"
        no_extra_spaces: true

    - name: Write instance name to inventory file
      community.general.ini_file:
        path: "{{ inventory_file }}"
        section: cloud:vars
        option: instance_name
        value: "{{ instance_name }}"
        no_extra_spaces: true
