---
- hosts: guest
  become: false
  vars:
    test_image_url: ""

  tasks:
    - name: check bios or uefi
      stat:
        path: /sys/firmware/efi

    - name: check partition size
      command: df -Th
      ignore_errors: true
      become: true

    - name: check disk partition table
      command: fdisk -l
      ignore_errors: true
      become: true

    - name: check mount table
      command: findmnt
      ignore_errors: true

    - name: Install podman and skopeo
      package:
        name:
          - podman
          - skopeo
        state: present
      become: true

    - name: Auth for RHEL private image
      command:
        podman login \
        -u "{{ lookup('env', 'QUAY_USERNAME') }}" \
        -p "{{ lookup('env', 'QUAY_PASSWORD') }}" \
        quay.io
      become: true

    - name: Install image
      command:
        "podman run \
         --rm \
         --privileged \
         --pid=host \
         -v /:/target \
         --security-opt label=type:unconfined_t \
         {{ test_image_url }} \
         bootc install to-filesystem --replace=alongside /target"
      become: true

    - name: Reboot to deploy new system
      reboot:
        post_reboot_delay: 60
        reboot_timeout: 180
      become: true
      ignore_errors: true

    - name: Wait for connection to become reachable/usable
      wait_for_connection:
        delay: 30
