---
- hosts: cloud
  gather_facts: false
  become: false

  tasks:
    - name: Remove openstack resources
      block:
        - name: remove openstack instance
          openstack.cloud.server:
            name: "{{ instance_name }}"
            state: absent
          ignore_errors: true

        - name: remove openstack keypair
          openstack.cloud.keypair:
            state: absent
            name: "kp-bootc-{{ random_num }}"
          ignore_errors: true

        - name: remove security group
          openstack.cloud.security_group:
            name: "sg-bootc-{{ random_num }}"
            state: absent
          ignore_errors: true
      when: platform == "openstack"

    - name: Remove GCP resources
      block:
        - name: "remove gcp instance {{ instance_name }}"
          command:
            "/usr/bin/gcloud compute instances delete {{ instance_name }} \
            --zone=us-central1-a \
            --delete-disks=all \
            --project={{ lookup('env', 'GCP_PROJECT') }}"
      when: platform == "gcp"

    - name: Remove AWS resources
      block:
        - name: terminate instance
          shell: |
            aws ec2 terminate-instances \
              --instance-ids "{{ instance_id }}"
          ignore_errors: true

        - name: wait until instance terminated
          shell: |
            aws ec2 wait instance-terminated \
              --instance-ids "{{ instance_id }}"

        - name: remove ec2 key
          shell: |
            aws ec2 delete-key-pair \
              --key-name "kp-bootc-{{ random_num }}"

        - name: Deregister AMI (delete associated snapshots too)
          block:
            - name: Get snapshot ID
              shell: |
                aws ec2 describe-images \
                  --image-ids "{{ ami_id }}" \
                  --query 'Images[0].[BlockDeviceMappings][0][0].Ebs.SnapshotId' \
                  --output text
              register: snapshot_result
            - name: Deregister AMI
              shell: |
                aws ec2 deregister-image \
                  --image-id "{{ ami_id }}"
            - name: Delete snapshot
              shell: |
                aws ec2 delete-snapshot \
                  --snapshot-id "{{ snapshot_result.stdout }}"
          when: ami_id != ""
      when: platform == "aws"

    - name: Destroy and undefine libvirt vm
      block:
        - name: "Destroy vm"
          command: virsh destroy {{ instance_name }}
          become: true
        - name: "Undefine vm"
          command: virsh undefine {{ instance_name }}
          become: true
        - name: "Delete disk file"
          command: virsh vol-delete --pool images "{{ rhel_guest_image_fname }}"
          become: true
      when: platform == "libvirt"

    - name: Cancel beaker job
      block:
        - name: "cancel beaker job {{ job_id }}"
          command: bkr job-cancel "{{ job_id }}"
      when: platform == "beaker"

    - name: Remove Azure resource group
      shell: |
        az group delete \
          --name {{ rg_name }} \
          --force-deletion-types Microsoft.Compute/virtualMachines \
          --no-wait \
          --yes
      when: platform == "azure"
