---
- hosts: guest
  become: false

  tasks:
    - name: Air-gapped upgrade
      block:
        - name: Mount virtiofs
          mount:
            path: /mnt
            src: mount_tag
            fstype: virtiofs
            state: ephemeral
          become: true

        - name: ls
          command: ls /mnt
          become: true

        - name: bootc switch
          command: bootc switch --transport dir /mnt
          become: true
      when:
        - air_gapped_dir | default('') != ""

    - name: bootc upgrade
      command: bootc upgrade
      become: true
      when:
        - air_gapped_dir | default('') == ""

    - name: Reboot to deploy new system
      reboot:
        post_reboot_delay: 60
        reboot_timeout: 180
      become: true
      ignore_errors: true

    - name: Wait for connection to become reachable/usable
      wait_for_connection:
        delay: 30
