---
- hosts: guest
  become: false
  vars:
    bootc_image: ""

  tasks:
    - name: Air-gapped upgrade
      block:
        - name: Mount virtiofs
          mount:
            path: /mnt
            src: mount_tag
            fstype: virtiofs
            state: ephemeral
          become: true

        - name: ls
          command: ls /mnt
          become: true

        - name: bootc switch
          command: bootc switch --transport dir /mnt
          become: true
      when:
        - air_gapped_dir | default('') != ""

    - name: determine installed image from localhost or quay.io
      shell: bootc status --json | jq -r '.status.booted.image.image.image'
      become: true
      register: result_bootc_status

    - name: switch to quay.io for upgrade
      command: bootc switch {{ bootc_image }}
      become: true
      when: "'localhost' in result_bootc_status.stdout"

    - name: bootc upgrade
      command: bootc upgrade
      become: true
      when:
        - air_gapped_dir | default('') == ""
        - "'localhost' not in result_bootc_status.stdout"

    # 20 minutes reboot timeout is for aws ec2 bare instance test
    - name: Reboot to deploy new system
      reboot:
        post_reboot_delay: 60
        reboot_timeout: 1200
      become: true
      ignore_errors: true

    - name: Wait for connection to become reachable/usable
      wait_for_connection:
        delay: 30

    - name: bootc booted status
      command: bootc status --booted
      become: true
