---
name: Build test runner container

on:
  workflow_dispatch:

jobs:
  build-upload:
    # Do not run this job on any fork repos
    if: github.repository == 'virt-s1/bootc-workflow-test'
    runs-on: ubuntu-latest
    steps:
      - name: Get User Permission
        id: user_permission
        uses: actions-cool/check-user-permission@956b2e73cdfe3bcb819bb7225e490cb3b18fd76e # v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout code
        if: steps.user_permission.outputs.require-result == 'true'
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Build container
        if: steps.user_permission.outputs.require-result == 'true'
        run: |
          sudo apt-get install -y podman
          podman build -t bootc-test-runner:x86_64 -f tools/Dockerfile tools
          podman push --creds "$QUAY_USERNAME":"$QUAY_PASSWORD" bootc-test-runner:x86_64 quay.io/rhel-edge/bootc-test-runner:x86_64
          podman push --creds "$QUAY_USERNAME":"$QUAY_PASSWORD" bootc-test-runner:x86_64 quay.io/rhel-edge/bootc-test-runner:latest
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
